baseURL = 'https://bittu.eu.org/'
languageCode = 'en-us'
title = 'My Personal Website'
enableRobotsTXT = true
disableKinds = ['rss']

# Enable Google Analytics by entering your tracking code
[services]
  [services.googleAnalytics]
    id = 'G-18YBHGT46W'

[params]
  description = "My personal website, built with Hugo"
  copyright = "Copyright &copy; 2023 Vedant and contributors."
  sidebarHeading = "Vedant Mohan Goyal"
  sidebarAbout = [
    "I am 17-year old student, who loves to code and learn new things.",
    """
    <b>Why bittu.eu.org?</b> <br>
    Because it's my nickname. Also, it's short and kind of fits for being in a domain name. <br>
    <b>eu.org</b> provides free subdomains for personal use. Read more about it <a href="https://nic.eu.org/">here</a>.
    """,
  ]
  # Contact page
    # Since this template is static, the contact form uses Google Forms.
    # The form embed the google form using its ID. You can find the ID of the
    # by looking at its url. Format: https://docs.google.com/forms/d/<form-id>/edit
    # Leave empty to disable the contact form.
    #
    # What you need to do for the setup?
    #
    # - get your form ID and put it below
  google_form_id = "1FAIpQLSfiRs08AJSU9rz-CnySllZQVkm0ji8Q32AD8CuMJB6ct0-17g"
          
  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact"

  [[params.navlinks]]
  name = "Docs↗️"
  url = "https://docs.bittu.eu.org"

  [[params.navlinks]]
  name = "Blog↗️"
  url = "https://blog.bittu.eu.org"

  [params.social]
  facebook      = ""
  googleplus    = ""
  email         = "contact@bittu.eu.org"
  twitter       = "https://twitter.com/vedantmgoyal"
  linkedin      = "https://www.linkedin.com/in/vedantmgoyal"
  stackoverflow = ""
  instagram     = "https://instagram.com/vedantmgoyal_"
  github        = "http://github.com/vedantmgoyal9"
  gitlab        = ""
  youtube       = "https://www.youtube.com/@vedantmgoyal"
  whatsapp      = ""
