name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issues:
    types: [opened, reopened]
  pull_request_target: # for label
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  get-commit:
    name: Get Commit
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      is-wpa-modified: ${{ steps.commit-info.outputs.wpa-modified }}
      is-wr-modified: ${{ steps.commit-info.outputs.wr-modified }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: npm install @commitlint/config-conventional
      - name: Commitlint (push)
        if: github.event_name == 'push'
        run: git log -1 --pretty=format:"%s" | npx commitlint --verbose
      - name: Commitlint (pull request)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Get commit information
        if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        run: |
          if [ '${{ github.event_name }}' == 'push' ]; then
            echo "::set-output name=wpa-modified::$(git diff --quiet HEAD HEAD~1 -- winget-pkgs-automation && echo false || echo true)"
            echo "::set-output name=wr-modified::$(git diff --quiet HEAD HEAD~1 -- winget-releaser && echo false || echo true)"
          else
            echo "::set-output name=wpa-modified::$(git diff --quiet ${{ github.pull_request.base.sha }} ${{ github.pull_request.head.sha }} -- winget-pkgs-automation && echo false || echo true)"
            echo "::set-output name=wr-modified::$(git diff --quiet ${{ github.pull_request.base.sha }} ${{ github.pull_request.head.sha }} -- winget-releaser && echo false || echo true)"
          fi
        id: commit-info
  winget-pkgs-automation:
    name: WinGet Automation (build)
    needs: get-commit
    if: needs.get-commit.outputs.is-wpa-modified == 'true' && (github.event_name == 'push' || github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: winget-pkgs-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/auth.yml
        id: auth
        with:
          app-id: ${{ secrets.BT_AP_ID}}
          private-key: ${{ secrets.BT_AP_PKY }}
          client-id: ${{ secrets.BT_CLNT_ID }}
          client-secret: ${{ secrets.BT_CLNT_SCRT }}
          installation-id: ${{ secrets.BT_CLNT_SCRT }}
      - name: Run Pester Checks
        run: |
          Invoke-Pester -Output Detailed
          git config --local user.name 'winget-pkgs-automation-bot[bot]'
          git config --local user.email '93540089+winget-pkgs-automation-bot[bot]@users.noreply.github.com'
          git commit -m "chore(wpa): update packages.txt" -- ./packages.txt
          git push https://x-access-token:${{ steps.auth.outputs.auth-token }}@github.com/vedantmgoyal2009/vedantmgoyal2009.git
      - uses: codecov/codecov-action@v2
        with:
          name: winget-pkgs-automation-codecov
          directory: ./
          files: ./coverage.xml
          working-directory: winget-pkgs-automation
          fail_ci_if_error: false
          verbose: true
  codeql-analysis:
    name: CodeQL (analyse)
    runs-on: ubuntu-latest
    needs: get-commit
    if: needs.get-commit.outputs.is-wr-modified == 'true' && (github.event_name == 'push' || github.event_name == 'pull_request')
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
        # language: [ 'java', 'javascript' ] <-- auto-detected, commented manually
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see https://github.com/github/codeql-action)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  label:
    name: Label
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4.0.0
        with:
          repo-token: ${{ env.auth-token }}
          configuration-path: '.github/labeler.yml'
          sync-labels: true
  greeting:
    name: Greeting
    if: github.event_name == 'issues' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ env.auth-token }}
          issue-message: 'Hello @${{ github.actor }}, thank you for submitting an issue!'
          pr-message: 'Hello @${{ github.actor }}, thank you submitting a pull request!'
