name: '[WPA] Automation'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: winget-pkgs-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Clone microsoft/winget-pkgs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: winget-pkgs-automation/winget-pkgs
          persist-credentials: false
          repository: microsoft/winget-pkgs
      - name: Authenticate GitHub Bot
        run: |
          # Initialize auth.js which will be used by the script to get bot token
          npm ci
          Write-Output 'async function main() {
            console.log((await require("@octokit/auth-app").createAppAuth({
              appId: ${{ secrets.BT_AP_ID }},
              privateKey: "${{ secrets.BT_AP_PKY }}",
              clientId: "${{ secrets.BT_CLNT_ID }}",
              clientSecret: "${{ secrets.BT_CLNT_SCRT }}",
              installationId: ${{ secrets.BT_INST_ID }},
            })({ type: "installation" })).token);
          }
          main();' | Out-File -FilePath auth.js
      - name: Run automation script
        run: .\src\Automation.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
        id: build
      - name: Upload wingetdev-build-log.txt
        if: steps.build.outputs.upload_log == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: wingetdev-build-log.txt
          path: winget-pkgs-automation/wingetdev-build-log.txt
          if-no-files-found: warn
          retention-days: 3
